/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangePassword: typeof import('./components/ChangePassword.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    ConfirmDialogHost: typeof import('./components/ConfirmDialogHost.vue')['default']
    CustomerForm: typeof import('./components/CustomerForm.vue')['default']
    CustomerSelector: typeof import('./components/CustomerSelector.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    PackagingMaterialForm: typeof import('./components/PackagingMaterialForm.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    ProductForm: typeof import('./components/ProductForm.vue')['default']
    RawMaterialForm: typeof import('./components/RawMaterialForm.vue')['default']
    RoleForm: typeof import('./components/RoleForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusChip: typeof import('./components/StatusChip.vue')['default']
    SupplierForm: typeof import('./components/SupplierForm.vue')['default']
    SupplierSelector: typeof import('./components/SupplierSelector.vue')['default']
    UserForm: typeof import('./components/UserForm.vue')['default']
    UserInformation: typeof import('./components/UserInformation.vue')['default']
  }
}
