/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/roles/': RouteRecordInfo<'/roles/', '/roles', Record<never, never>, Record<never, never>>,
    '/roles/[id]/': RouteRecordInfo<'/roles/[id]/', '/roles/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/roles/[id]/editar': RouteRecordInfo<'/roles/[id]/editar', '/roles/:id/editar', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/roles/[id]/permisos': RouteRecordInfo<'/roles/[id]/permisos', '/roles/:id/permisos', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/roles/nuevo': RouteRecordInfo<'/roles/nuevo', '/roles/nuevo', Record<never, never>, Record<never, never>>,
    '/usuarios/': RouteRecordInfo<'/usuarios/', '/usuarios', Record<never, never>, Record<never, never>>,
    '/usuarios/[id]/': RouteRecordInfo<'/usuarios/[id]/', '/usuarios/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/usuarios/[id]/editar': RouteRecordInfo<'/usuarios/[id]/editar', '/usuarios/:id/editar', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/usuarios/nuevo': RouteRecordInfo<'/usuarios/nuevo', '/usuarios/nuevo', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'src/pages/403.vue': {
      routes: '/403'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/profile.vue': {
      routes: '/profile'
      views: never
    }
    'src/pages/roles/index.vue': {
      routes: '/roles/'
      views: never
    }
    'src/pages/roles/[id]/index.vue': {
      routes: '/roles/[id]/'
      views: never
    }
    'src/pages/roles/[id]/editar.vue': {
      routes: '/roles/[id]/editar'
      views: never
    }
    'src/pages/roles/[id]/permisos.vue': {
      routes: '/roles/[id]/permisos'
      views: never
    }
    'src/pages/roles/nuevo.vue': {
      routes: '/roles/nuevo'
      views: never
    }
    'src/pages/usuarios/index.vue': {
      routes: '/usuarios/'
      views: never
    }
    'src/pages/usuarios/[id]/index.vue': {
      routes: '/usuarios/[id]/'
      views: never
    }
    'src/pages/usuarios/[id]/editar.vue': {
      routes: '/usuarios/[id]/editar'
      views: never
    }
    'src/pages/usuarios/nuevo.vue': {
      routes: '/usuarios/nuevo'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
